spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://task-management-db.c9ys2ao8ofsg.ap-south-1.rds.amazonaws.com:3306/TaskManagementDB
    username: Janani1423
    password: janani1423
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            mode: none

  application:
    name: TASK-MANAGEMENT-API

  security:
    cors:
      allowCredentials: true
      exposedHeaders: Authorization
